add a `k` argument to random commands
ubq323/cn2 pull request #4
Opened 2021-02-03 17:40 UTC by ivancr72

i pasted this into vscode and there aren't any warnings 
i hope this isn't full of bugs

2021-02-03 18:06 UTC, ubq323 requested changes

2021-02-03 18:06 UTC, ubq323 commented on cn2/__main__.py
> +async def random(ctx, a: int = 10, b: int = 1, k: int = 1):
why have you changed this back

2021-02-03 18:23 UTC, ivancr72 commented on cn2/__main__.py
> +async def random(ctx, a: int = 10, b: int = 1, k: int = 1):
we aren't importing random anyway
and Optional[] is not needed

2021-02-03 22:27 UTC, ubq323 requested changes

2021-02-03 22:27 UTC, ubq323 commented on cn2/__main__.py
> +async def random_emoji(ctx, k: int = 10):
shouldn't the default be 1

2021-02-06 14:30 UTC, ivancr72 commented on cn2/__main__.py
> +async def random_emoji(ctx, k: int = 10):
done

2022-12-07 22:53 UTC, closed without merging